// Generated by LiveScript 1.6.0
(function(){
  var implies, labeled, anyParam, anyPoint, anyAngleValue, mkAngle, anyAngle, anySegment, anyLine, anyRay, anyRadius, anyCircle, anyTriangle, Any, testTests;
  implies = function(P, Q){
    if (P) {
      return Q;
    } else {
      return true;
    }
  };
  labeled = curry$(function(f, l){
    return function(){
      var x, res$, i$, to$;
      res$ = [];
      for (i$ = 0, to$ = arguments.length; i$ < to$; ++i$) {
        res$.push(arguments[i$]);
      }
      x = res$;
      if (l) {
        return f.apply(null, x).label(l);
      } else {
        return f.apply(null, x);
      }
    };
  });
  anyParam = function(a, b){
    a == null && (a = 0);
    b == null && (b = 1);
    return anyNum().range(a, b).precision(0.01).ascending();
  };
  anyPoint = function(l){
    return args(anyPos()).iso(labeled(point, l), function(p){
      return [p.xy];
    });
  };
  anyAngleValue = function(){
    return new ArbitraryNumber(0, 360).precision(1).ascending();
  };
  mkAngle = function(v, s, e){
    var x$;
    x$ = new Angle();
    x$.vertex = v;
    x$.start = s;
    x$.end = e;
    return x$;
  };
  anyAngle = function(){
    return args(anyPoint(), anyAngleValue(), anyAngleValue()).iso(mkAngle, function(a){
      return [a.vertex, a.start, a.end];
    });
  };
  anySegment = function(l){
    return args(anyPoint(), anyPoint()).iso(labeled(segment, l), function(s){
      return [s.point(0), s.point(1)];
    });
  };
  anyLine = function(l){
    return args(anyPoint(), anyPoint()).iso(labeled(line, l), function(l){
      return [l.point(0), l.point(1)];
    });
  };
  anyRay = function(l){
    return args(anyPoint(), anyAngleValue()).iso(labeled(ray, l), function(r){
      return [r.start, r.angle(0)];
    });
  };
  anyRadius = function(){
    return anyNum().range(1, paperSize / 4).precision(0.25).ascending();
  };
  anyCircle = function(){
    return args(anyRadius(), anyPoint()).iso(circle, function(c){
      return [c.R, c.center];
    }).ascending();
  };
  anyTriangle = function(){
    return args(anyPoint(), anyPoint(), anyPoint()).iso(new Triangle, function(it){
      return it.vertices;
    }).filter(function(it){
      return it.isNontrivial;
    });
  };
  Any = {
    num: anyNum,
    param: anyParam,
    point: anyPoint,
    xy: anyPos,
    angle: anyAngle,
    angleValue: anyAngleValue,
    line: anyLine,
    ray: anyRay,
    segment: anySegment,
    circle: anyCircle,
    triangle: anyTriangle
  };
  window.Any = Any;
  testTests = {
    name: 'Tests',
    skip: false,
    log: true,
    suite: [
      {
        name: "1",
        'for': [anyNum().range(0, 100).precision(0.1)],
        hold: function(n){
          return n === 4;
        },
        number: 10
      }, {
        name: "2",
        'for': [anyNum(), anyNum()],
        hold: function(n, m){
          return n >= m;
        },
        log: false
      }, {
        name: "3",
        'for': [anyCircle(), anyPoint()],
        assuming: [function(c, p){
          return c.R > 1 && c.center.isNotEqual(p);
        }],
        hold: function(c, p){
          return !c.isEnclosing(p);
        }
      }
    ]
  };
  window.testTests = testTests;
  function curry$(f, bound){
    var context,
    _curry = function(args) {
      return f.length > 1 ? function(){
        var params = args ? args.concat() : [];
        context = bound ? context || this : this;
        return params.push.apply(params, arguments) <
            f.length && arguments.length ?
          _curry.call(context, params) : f.apply(context, params);
      } : f;
    };
    return _curry();
  }
}).call(this);
