// Generated by LiveScript 1.6.0
(function(){
  var equal, nequal, gequal, lequal, equalMod;
  equal = function(a, b){
    switch (false) {
    case !(Number.isFinite(a) && Number.isFinite(b)):
      return abs(a - b) < 1e-10 || abs(a - b) < 1e-10 * abs(a + b);
    case !(a instanceof Figure && a instanceof Figure):
      return a.isEqual(b);
    case !(Array.isArray(a) && Array.isArray(b)):
      return a.length === b.length && a.every(function(x, i){
        return equal(x, b[i]);
      });
    default:
      return a === b;
    }
  };
  nequal = function(a, b){
    return !equal(a, b);
  };
  gequal = function(a, b){
    return a > b || equal(a, b);
  };
  lequal = function(a, b){
    return a < b || equal(a, b);
  };
  equalMod = function(m){
    return function(a, b){
      var ref$;
      return equal(((a) % (ref$ = m) + ref$) % ref$, ((b) % (ref$ = m) + ref$) % ref$);
    };
  };
  window.equal = equal;
  window.nequal = nequal;
  window.gequal = gequal;
  window.lequal = lequal;
  window.equalMod = equalMod;
}).call(this);
